
export const FILTER_TODO = 'FILTER_TODO';
export const ADD_TODO = 'ADD_TODO';
export const ARCHIVE_TODO = 'ARCHIVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const SEND_TODO = 'SEND_TODO';

export const SEND_TODO_STATE_SUCCESS = 'SEND_TODO_STATE_SUCCESS';
export const SEND_TODO_STATE_REQUESTED = 'SEND_TODO_STATE_REQUESTED';
export const SEND_TODO_STATE_FAILED = 'SEND_TODO_STATE_FAILED';

export const FETCH_TODO_STATE_SUCCESS = 'FETCH_TODO_STATE_SUCCESS';
export const FETCH_TODO_STATE_REQUESTED = 'FETCH_TODO_STATE_REQUESTED';
export const FETCH_TODO_STATE_FAILED = 'FETCH_TODO_STATE_FAILED';
